apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: configaudits.kapi-example.comradequinn.github.io
spec:
  group: kapi-example.comradequinn.github.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                message:
                  type: string
              required:
                - message
          required:
            - spec
  scope: Namespaced
  names:
    plural: configaudits
    singular: configaudit
    kind: ConfigAudit
    shortNames:
      - ca
