apiVersion: v1
kind: ServiceAccount
metadata:
  name: kapi-example
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: resource-controller
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["kapi-example.comradequinn.github.io"]
    resources: ["configaudits"]
    verbs: ["update", "create", "delete", "get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: resource-controller-binding
subjects:
  - kind: ServiceAccount
    name: kapi-example
roleRef:
  kind: ClusterRole
  name: resource-controller
  apiGroup: rbac.authorization.k8s.io
